server:
  port: ${SERVER_PORT:8005}
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:user}
    password: ${SMTP_PASS:password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

    consumer:
      group-id: ${KAFKA_GROUP:notification}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.sprintforge.notification.*"
        spring.json.use.type.headers: false

    listener:
      concurrency: ${KAFKA_CONCURRENCY:3}
      ack-mode: record

    topics:
      email-verification-requested: ${TOPIC_EMAIL_VERIFICATION_REQUESTED:email.verification.requested}
      email-sprint-created: ${KAFKA_TOPIC_EMAIL_SPRINT_CREATED:email.sprint.created}

    groups:
      default-group: ${spring.kafka.consumer.group-id}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:INFO}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:INFO}

app:
  verification:
    base-url: ${LINK_VERIFY_PATH:http://localhost:8000}
    endpoint: ${VERIFY_PATH:/api/v1/auth/verify-email}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${PUBLIC_HOST:localhost}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/
